### ISSUE TITLE
Coordinates Issue

### ISSUE THREAD

**Issue by dogyg** [Yellowstrawberrys/RandomSpawn#1]
I'm currently using a plugin called CoordinateOffset, and my Randomspawn setting.yaml values are as follows.

```yaml
coordinates:
  type: Custom
  # Custom
  centerX: 0 # Needs to be Integer
  centerZ: 0 # Needs to be Integer
  maxX: 100000 # Needs to be Integer
  maxZ: 100000 # Needs to be Integer
  canSpawnInWater: false # Needs to be boolean(true or false)
```
But even with these settings, it's killed by worldborder, probably because of the randomization of the CoordinateOffset.

Added: I tried removing the CoordinateOffset plugin from the plugin file and getting it to work, but it still gets killed by worldborder and strange coordinate. Is there something I'm doing wrong?
